version: "3.7"

services:
  microservico-busca-jurisprudencia-stj:
    image: talentssoftware/microservico-busca-jurisprudencia-stj
    ports:
      - { target: 3000, published: 3000, protocol: tcp, mode: host }
    networks:
      - default
    environment:
        NODE_ENV: production
        PORT: 3000
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/stj
        JWT_SECRET: secret
        JWT_EXPIRES_IN: 90d
        ARGON_SALT: secret
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s

  postgres:
    image: postgres:16.1-alpine
    environment:
      LANG: "pt_BR.UTF-8"
      TZ: "America/Sao_Paulo"
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=pt-BR"

      POSTGRES_DB: "stj"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: "postgres"
    networks:
        - default

networks:
  default: