version: "3.7"

services:
  mbjstj:
    image: blx32/mbjstj
    ports:
      - { target: 80, published: 80, protocol: tcp, mode: host }
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s

  chromium:
    image: blx32/chromium
    command:
      - --no-sandbox
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
    security_opt:
      - seccomp=/usr/src/app/chrome.json
    ports:
      - { target: 9222, published: 9222, protocol: tcp, mode: host }
    networks:
        - default
    shm_size: 1gb
    cap_add:
      - SYS_ADMIN
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  default: